# Generated by Django 4.2.2 on 2023-06-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='category',
            field=models.CharField(max_length=200),
        ),
    ]
